-- --------------------------------------------------------

-- 
-- Table structure for table `paises`
-- 

CREATE TABLE `paises` (
  `id` int(6) NOT NULL auto_increment,
  `nombrepais` varchar(250) NOT NULL default '',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=242 ;

-- 
-- Dumping data for table `paises`
-- 

INSERT INTO `paises` VALUES (1, 'Afghanistan');
INSERT INTO `paises` VALUES (2, 'Aringland Islands');
INSERT INTO `paises` VALUES (3, 'Albania');
INSERT INTO `paises` VALUES (4, 'Algeria');
INSERT INTO `paises` VALUES (5, 'American Samoa');
INSERT INTO `paises` VALUES (6, 'Andorra');
INSERT INTO `paises` VALUES (7, 'Angola');
INSERT INTO `paises` VALUES (8, 'Anguilla');
INSERT INTO `paises` VALUES (9, 'Antarctica');
INSERT INTO `paises` VALUES (10, 'Antigua and Barbuda');
INSERT INTO `paises` VALUES (11, 'Argentina');
INSERT INTO `paises` VALUES (12, 'Armenia');
INSERT INTO `paises` VALUES (13, 'Aruba');
INSERT INTO `paises` VALUES (14, 'Australia');
INSERT INTO `paises` VALUES (15, 'Austria');
INSERT INTO `paises` VALUES (16, 'Azerbaijan');
INSERT INTO `paises` VALUES (17, 'Bahamas');
INSERT INTO `paises` VALUES (18, 'Bahrain');
INSERT INTO `paises` VALUES (19, 'Bangladesh');
INSERT INTO `paises` VALUES (20, 'Barbados');
INSERT INTO `paises` VALUES (21, 'Belarus');
INSERT INTO `paises` VALUES (22, 'Belgium');
INSERT INTO `paises` VALUES (23, 'Belize');
INSERT INTO `paises` VALUES (24, 'Benin');
INSERT INTO `paises` VALUES (25, 'Bermuda');
INSERT INTO `paises` VALUES (26, 'Bhutan');
INSERT INTO `paises` VALUES (27, 'Bolivia');
INSERT INTO `paises` VALUES (28, 'Bosnia and Herzegovina');
INSERT INTO `paises` VALUES (29, 'Botswana');
INSERT INTO `paises` VALUES (30, 'Bouvet Island');
INSERT INTO `paises` VALUES (31, 'Brazil');
INSERT INTO `paises` VALUES (32, 'British Indian Ocean territory');
INSERT INTO `paises` VALUES (33, 'Brunei Darussalam');
INSERT INTO `paises` VALUES (34, 'Bulgaria');
INSERT INTO `paises` VALUES (35, 'Burkina Faso');
INSERT INTO `paises` VALUES (36, 'Burundi');
INSERT INTO `paises` VALUES (37, 'Cambodia');
INSERT INTO `paises` VALUES (38, 'Cameroon');
INSERT INTO `paises` VALUES (39, 'Canada');
INSERT INTO `paises` VALUES (40, 'Cape Verde');
INSERT INTO `paises` VALUES (41, 'Cayman Islands');
INSERT INTO `paises` VALUES (42, 'Central African Republic');
INSERT INTO `paises` VALUES (43, 'Chad');
INSERT INTO `paises` VALUES (44, 'Chile');
INSERT INTO `paises` VALUES (45, 'China');
INSERT INTO `paises` VALUES (46, 'Christmas Island');
INSERT INTO `paises` VALUES (47, 'Cocos (Keeling) Islands');
INSERT INTO `paises` VALUES (48, 'Colombia');
INSERT INTO `paises` VALUES (49, 'Comoros');
INSERT INTO `paises` VALUES (50, 'Congo');
INSERT INTO `paises` VALUES (51, 'Congo');
INSERT INTO `paises` VALUES (52, ' Democratic Republic');
INSERT INTO `paises` VALUES (53, 'Cook Islands');
INSERT INTO `paises` VALUES (54, 'Costa Rica');
INSERT INTO `paises` VALUES (55, 'Ivory Coast (Ivory Coast)');
INSERT INTO `paises` VALUES (56, 'Croatia (Hrvatska)');
INSERT INTO `paises` VALUES (57, 'Cuba');
INSERT INTO `paises` VALUES (58, 'Cyprus');
INSERT INTO `paises` VALUES (59, 'Czech Republic');
INSERT INTO `paises` VALUES (60, 'Denmark');
INSERT INTO `paises` VALUES (61, 'Djibouti');
INSERT INTO `paises` VALUES (62, 'Dominica');
INSERT INTO `paises` VALUES (63, 'Dominican Republic');
INSERT INTO `paises` VALUES (64, 'East Timor');
INSERT INTO `paises` VALUES (65, 'Ecuador');
INSERT INTO `paises` VALUES (66, 'Egypt');
INSERT INTO `paises` VALUES (67, 'El Salvador');
INSERT INTO `paises` VALUES (68, 'Equatorial Guinea');
INSERT INTO `paises` VALUES (69, 'Eritrea');
INSERT INTO `paises` VALUES (70, 'Estonia');
INSERT INTO `paises` VALUES (71, 'Ethiopia');
INSERT INTO `paises` VALUES (72, 'Falkland Islands');
INSERT INTO `paises` VALUES (73, 'Faroe Islands');
INSERT INTO `paises` VALUES (74, 'Fiji');
INSERT INTO `paises` VALUES (75, 'Finland');
INSERT INTO `paises` VALUES (76, 'France');
INSERT INTO `paises` VALUES (77, 'French Guiana');
INSERT INTO `paises` VALUES (78, 'French Polynesia');
INSERT INTO `paises` VALUES (79, 'French Southern Territories');
INSERT INTO `paises` VALUES (80, 'Gabon');
INSERT INTO `paises` VALUES (81, 'Gambia');
INSERT INTO `paises` VALUES (82, 'Georgia');
INSERT INTO `paises` VALUES (83, 'Germany');
INSERT INTO `paises` VALUES (84, 'Ghana');
INSERT INTO `paises` VALUES (85, 'Gibraltar');
INSERT INTO `paises` VALUES (86, 'Greece');
INSERT INTO `paises` VALUES (87, 'Greenland');
INSERT INTO `paises` VALUES (88, 'Grenada');
INSERT INTO `paises` VALUES (89, 'Guadeloupe');
INSERT INTO `paises` VALUES (90, 'Guam');
INSERT INTO `paises` VALUES (91, 'Guatemala');
INSERT INTO `paises` VALUES (92, 'Guinea');
INSERT INTO `paises` VALUES (93, 'Guinea-Bissau');
INSERT INTO `paises` VALUES (94, 'Guyana');
INSERT INTO `paises` VALUES (95, 'Haiti');
INSERT INTO `paises` VALUES (96, 'Heard and McDonald Islands');
INSERT INTO `paises` VALUES (97, 'Honduras');
INSERT INTO `paises` VALUES (98, 'Hong Kong');
INSERT INTO `paises` VALUES (99, 'Hungary');
INSERT INTO `paises` VALUES (100, 'Iceland');
INSERT INTO `paises` VALUES (101, 'India');
INSERT INTO `paises` VALUES (102, 'Indonesia');
INSERT INTO `paises` VALUES (103, 'Iran');
INSERT INTO `paises` VALUES (104, 'Iraq');
INSERT INTO `paises` VALUES (105, 'Ireland');
INSERT INTO `paises` VALUES (106, 'Israel');
INSERT INTO `paises` VALUES (107, 'Italy');
INSERT INTO `paises` VALUES (108, 'Jamaica');
INSERT INTO `paises` VALUES (109, 'Japan');
INSERT INTO `paises` VALUES (110, 'Jordan');
INSERT INTO `paises` VALUES (111, 'Kazakhstan');
INSERT INTO `paises` VALUES (112, 'Kenya');
INSERT INTO `paises` VALUES (113, 'Kiribati');
INSERT INTO `paises` VALUES (114, 'Korea (north)');
INSERT INTO `paises` VALUES (115, 'Korea (south)');
INSERT INTO `paises` VALUES (116, 'Kuwait');
INSERT INTO `paises` VALUES (117, 'Kyrgyzstan');
INSERT INTO `paises` VALUES (118, 'Lao People''s Democratic Republic');
INSERT INTO `paises` VALUES (119, 'Latvia');
INSERT INTO `paises` VALUES (120, 'Lebanon');
INSERT INTO `paises` VALUES (121, 'Lesotho');
INSERT INTO `paises` VALUES (122, 'Liberia');
INSERT INTO `paises` VALUES (123, 'Libyan Arab Jamahiriya');
INSERT INTO `paises` VALUES (124, 'Liechtenstein');
INSERT INTO `paises` VALUES (125, 'Lithuania');
INSERT INTO `paises` VALUES (126, 'Luxembourg');
INSERT INTO `paises` VALUES (127, 'Macao');
INSERT INTO `paises` VALUES (128, 'Macedonia');
INSERT INTO `paises` VALUES (129, 'Madagascar');
INSERT INTO `paises` VALUES (130, 'Malawi');
INSERT INTO `paises` VALUES (131, 'Malaysia');
INSERT INTO `paises` VALUES (132, 'Maldives');
INSERT INTO `paises` VALUES (133, 'Mali');
INSERT INTO `paises` VALUES (134, 'Malta');
INSERT INTO `paises` VALUES (135, 'Marshall Islands');
INSERT INTO `paises` VALUES (136, 'Martinique');
INSERT INTO `paises` VALUES (137, 'Mauritania');
INSERT INTO `paises` VALUES (138, 'Mauritius');
INSERT INTO `paises` VALUES (139, 'Mayotte');
INSERT INTO `paises` VALUES (140, 'Mexico');
INSERT INTO `paises` VALUES (141, 'Micronesia');
INSERT INTO `paises` VALUES (142, 'Moldova');
INSERT INTO `paises` VALUES (143, 'Monaco');
INSERT INTO `paises` VALUES (144, 'Mongolia');
INSERT INTO `paises` VALUES (145, 'Montserrat');
INSERT INTO `paises` VALUES (146, 'Morocco');
INSERT INTO `paises` VALUES (147, 'Mozambique');
INSERT INTO `paises` VALUES (148, 'Myanmar');
INSERT INTO `paises` VALUES (149, 'Namibia');
INSERT INTO `paises` VALUES (150, 'Nauru');
INSERT INTO `paises` VALUES (151, 'Nepal');
INSERT INTO `paises` VALUES (152, 'Netherlands');
INSERT INTO `paises` VALUES (153, 'Netherlands Antilles');
INSERT INTO `paises` VALUES (154, 'New Caledonia');
INSERT INTO `paises` VALUES (155, 'New Zealand');
INSERT INTO `paises` VALUES (156, 'Nicaragua');
INSERT INTO `paises` VALUES (157, 'Niger');
INSERT INTO `paises` VALUES (158, 'Nigeria');
INSERT INTO `paises` VALUES (159, 'Niue');
INSERT INTO `paises` VALUES (160, 'Norfolk Island');
INSERT INTO `paises` VALUES (161, 'Northern Mariana Islands');
INSERT INTO `paises` VALUES (162, 'Norway');
INSERT INTO `paises` VALUES (163, 'Oman');
INSERT INTO `paises` VALUES (164, 'Pakistan');
INSERT INTO `paises` VALUES (165, 'Palau');
INSERT INTO `paises` VALUES (166, 'Palestinian Territories');
INSERT INTO `paises` VALUES (167, 'Panama');
INSERT INTO `paises` VALUES (168, 'Papua New Guinea');
INSERT INTO `paises` VALUES (169, 'Paraguay');
INSERT INTO `paises` VALUES (170, 'Peru');
INSERT INTO `paises` VALUES (171, 'Philippines');
INSERT INTO `paises` VALUES (172, 'Pitcairn');
INSERT INTO `paises` VALUES (173, 'Poland');
INSERT INTO `paises` VALUES (174, 'Portugal');
INSERT INTO `paises` VALUES (175, 'Puerto Rico');
INSERT INTO `paises` VALUES (176, 'Qatar');
INSERT INTO `paises` VALUES (177, 'Runion');
INSERT INTO `paises` VALUES (178, 'Romania');
INSERT INTO `paises` VALUES (179, 'Russian Federation');
INSERT INTO `paises` VALUES (180, 'Rwanda');
INSERT INTO `paises` VALUES (181, 'Saint Helena');
INSERT INTO `paises` VALUES (182, 'Saint Kitts and Nevis');
INSERT INTO `paises` VALUES (183, 'Saint Lucia');
INSERT INTO `paises` VALUES (184, 'Saint Pierre and Miquelon');
INSERT INTO `paises` VALUES (185, 'Saint Vincent and the Grenadines');
INSERT INTO `paises` VALUES (186, 'Samoa');
INSERT INTO `paises` VALUES (187, 'San Marino');
INSERT INTO `paises` VALUES (188, 'Sao Tome and Principe');
INSERT INTO `paises` VALUES (189, 'Saudi Arabia');
INSERT INTO `paises` VALUES (190, 'Senegal');
INSERT INTO `paises` VALUES (191, 'Serbia and Montenegro');
INSERT INTO `paises` VALUES (192, 'Seychelles');
INSERT INTO `paises` VALUES (193, 'Sierra Leone');
INSERT INTO `paises` VALUES (194, 'Singapore');
INSERT INTO `paises` VALUES (195, 'Slovakia');
INSERT INTO `paises` VALUES (196, 'Slovenia');
INSERT INTO `paises` VALUES (197, 'Solomon Islands');
INSERT INTO `paises` VALUES (198, 'Somalia');
INSERT INTO `paises` VALUES (199, 'South Africa');
INSERT INTO `paises` VALUES (200, 'South Georgia and the South Sandwich Islands');
INSERT INTO `paises` VALUES (201, 'Spain');
INSERT INTO `paises` VALUES (202, 'Sri Lanka');
INSERT INTO `paises` VALUES (203, 'Sudan');
INSERT INTO `paises` VALUES (204, 'Suriname');
INSERT INTO `paises` VALUES (205, 'Svalbard and Jan Mayen Islands');
INSERT INTO `paises` VALUES (206, 'Swaziland');
INSERT INTO `paises` VALUES (207, 'Sweden');
INSERT INTO `paises` VALUES (208, 'Switzerland');
INSERT INTO `paises` VALUES (209, 'Syria');
INSERT INTO `paises` VALUES (210, 'Taiwan');
INSERT INTO `paises` VALUES (211, 'Tajikistan');
INSERT INTO `paises` VALUES (212, 'Tanzania');
INSERT INTO `paises` VALUES (213, 'Thailand');
INSERT INTO `paises` VALUES (214, 'Togo');
INSERT INTO `paises` VALUES (215, 'Tokelau');
INSERT INTO `paises` VALUES (216, 'Tonga');
INSERT INTO `paises` VALUES (217, 'Trinidad and Tobago');
INSERT INTO `paises` VALUES (218, 'Tunisia');
INSERT INTO `paises` VALUES (219, 'Turkey');
INSERT INTO `paises` VALUES (220, 'Turkmenistan');
INSERT INTO `paises` VALUES (221, 'Turks and Caicos Islands');
INSERT INTO `paises` VALUES (222, 'Tuvalu');
INSERT INTO `paises` VALUES (223, 'Uganda');
INSERT INTO `paises` VALUES (224, 'Ukraine');
INSERT INTO `paises` VALUES (225, 'United Arab Emirates');
INSERT INTO `paises` VALUES (226, 'United Kingdom');
INSERT INTO `paises` VALUES (227, 'United States of America');
INSERT INTO `paises` VALUES (228, 'Uruguay');
INSERT INTO `paises` VALUES (229, 'Uzbekistan');
INSERT INTO `paises` VALUES (230, 'Vanuatu');
INSERT INTO `paises` VALUES (231, 'Vatican City');
INSERT INTO `paises` VALUES (232, 'Venezuela');
INSERT INTO `paises` VALUES (233, 'Vietnam');
INSERT INTO `paises` VALUES (234, 'Virgin Islands (British)');
INSERT INTO `paises` VALUES (235, 'Virgin Islands (US)');
INSERT INTO `paises` VALUES (236, 'Wallis and Futuna Islands');
INSERT INTO `paises` VALUES (237, 'Western Sahara');
INSERT INTO `paises` VALUES (238, 'Yemen');
INSERT INTO `paises` VALUES (239, 'Zaire');
INSERT INTO `paises` VALUES (240, 'Zambia');
INSERT INTO `paises` VALUES (241, 'Zimbabwe');
